id: P7B720FF8
initial_creation_type: ocr
source_metadata:
  volumes:
    66671946dcef45cbaf94fea45257f0ca:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: གཙུག་ཏོར་དྲི་མེད་ཀྱི་གཟུངས་ཆོག།
      total_pages: 1044
      volume_number: 38
